keys:
  - &host_nixos age1nk8leddm7qeat9j0320hpn5r2rjkhprp00k7tx8yv7dda7xks9zsq9gc5n
  - &host_omen age1860wzxx9w4ld9jx9d6khvef7malq888qmge2gc4p2y949vlppvjqvxypaq

creation_rules:
  - path_regex: \.env$
    key_groups:
      - age:
          - *host_nixos
          - *host_omen
